# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GLOBAL_VAR: "This is a global environment variable"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print environment variables
      run: |
        echo "GLOBAL_VAR is $GLOBAL_VAR"
        echo "LOCAL_VAR is $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is a local environment variable"

    - name: Run a script with environment variables
      run: |
        echo "Running a script with env vars"
      env:
        SCRIPT_VAR: "This is a script-specific environment variable"

    - name: Use environment variables in commands
      run: |
        echo "Combining variables: $GLOBAL_VAR and $SCRIPT_VAR"