# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GLOBAL_VAR: "Global1"
      GLOBAL_VAR2: "None"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print environment variables
      run: |
        echo "GLOBAL_VAR is $GLOBAL_VAR"
        echo "LOCAL_VAR is $LOCAL_VAR"
      env:
        local_var: "This is a local environment variable"

    - name: Run a script with environment variables
      run: |
        echo "Running a script with env vars"
        export GLOBAL_VAR2=$(./varscript.sh)
      env:
        SCRIPT_VAR: "fromScriptVar"

    - name: Use environment variables in commands
      run: |
        echo "Combining variables: $GLOBAL_VAR, $GLOBAL_VAR2 and $SCRIPT_VAR"